// GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Run `npm run gallery` after changing scripts/gallery-manifest.mjs.

export type GalleryImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const gallery: Record<string, GalleryImage> = {
  "pub-athercare-ieee": {
    src: "/images/gallery/pub-athercare-ieee.webp",
    width: 1079,
    height: 515,
    blurDataURL: "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAAAwAQCdASoOAAcAAwBSJaQAA3AA/vTqD39ntUjOVgAAAA==",
  },
  "pub-athercare-presented": {
    src: "/images/gallery/pub-athercare-presented.webp",
    width: 1079,
    height: 765,
    blurDataURL: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoOAAoAAwBSJYwCdH8AFN5p88AA/cJ4mpGfh5qzUROw4BJ/QAAAAA==",
  },
  "pub-ijatem": {
    src: "/images/gallery/pub-ijatem.webp",
    width: 1080,
    height: 712,
    blurDataURL: "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoOAAkAAwBSJZQCdADwR3Kq0AD+mk18rEE9wXaJnZ/W9esdk7goPHxUAAA=",
  },
  "award-icrcct-stage": {
    src: "/images/gallery/award-icrcct-stage.webp",
    width: 1047,
    height: 750,
    blurDataURL: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoOAAoAAwBSJaACdIExF9jkZgAA/mADOSQx2c9MFIQyv+lIvHAkLjSSDLmZq/DgAAA=",
  },
  "award-icrcct-trophy": {
    src: "/images/gallery/award-icrcct-trophy.webp",
    width: 1080,
    height: 1311,
    blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoOABEAPt1apkyopSOiMAgBEBuJYgCdABe4BojlZjzZMfwAAP7mhvYEi16mHzWDGXhLQWyXPxqF6rriz5go+E+mG97PFs5JD0aL0DogHnXCeQZU2AA=",
  },
  "cert-aws-foundations": {
    src: "/images/gallery/cert-aws-foundations.webp",
    width: 1079,
    height: 943,
    blurDataURL: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAABwAQCdASoOAAwAAwBSJZQCdAFAAAD+8n7mvBM6dTrtlKQmqAAAAA==",
  },
  "cert-aws-security": {
    src: "/images/gallery/cert-aws-security.webp",
    width: 1080,
    height: 1034,
    blurDataURL: "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADwAQCdASoOAA0AAwBSJZQCdAEPAeIC3gAA/vd4MTVD+Kv4cMLGsAAA",
  },
  "cert-uipath": {
    src: "/images/gallery/cert-uipath.webp",
    width: 960,
    height: 830,
    blurDataURL: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoOAAwAAwBSJbAAAuffEY669bAA/vY8IlsbNq8Jjxz8BLaQAmxnA/7p9CL7H/7Xor458gTFZAAAAA==",
  },
  "cert-uipath-cohort": {
    src: "/images/gallery/cert-uipath-cohort.webp",
    width: 1079,
    height: 1255,
    blurDataURL: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoOABAAAwBSJaQAAu19uX+tYwAA/vjab/ztRBAFqQOwUxYad+UxzUH0VbSVPEQg2BnitoAA",
  },
  "cert-aspire": {
    src: "/images/gallery/cert-aspire.webp",
    width: 1079,
    height: 853,
    blurDataURL: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoOAAsAAwBSJQAAUlCsd8SAAP7wtn7z+0dYyexFgt6qxSASc/qLQR3FUlK1oUm3laYAAA==",
  },
  "cert-tcs-ion": {
    src: "/images/gallery/cert-tcs-ion.webp",
    width: 1079,
    height: 779,
    blurDataURL: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAAAQAgCdASoOAAoAAwBSJZQCdH8AGBwsNBwAAP71B4tgY1Ig4r3lT6Da9sZXqr1VVwAAAA==",
  },
  "cert-palo-cloud": {
    src: "/images/gallery/cert-palo-cloud.webp",
    width: 1080,
    height: 828,
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoOAAsAAwBSJagCdH8AGBp5F6AA/vgKbvUYdeqlsHxkLGO/6rkl0WfRWQbfNte3WlAhIqYUAAA=",
  },
  "cert-palo-network": {
    src: "/images/gallery/cert-palo-network.webp",
    width: 1080,
    height: 842,
    blurDataURL: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoOAAsAAwBSJagCdFQAA5WVp+bAAP72NFH0CLG9ewU0ehWtA5JWSMld3+kgeP/yTCLG1lckkAX0AA==",
  },
  "cert-ict-rpa": {
    src: "/images/gallery/cert-ict-rpa.webp",
    width: 1079,
    height: 654,
    blurDataURL: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAABQAQCdASoOAAgAAwBSJZQABAAAAP7uO4WBNecTi5Lndi8dwEAAAA==",
  },
  "cert-mindler": {
    src: "/images/gallery/cert-mindler.webp",
    width: 1080,
    height: 738,
    blurDataURL: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoOAAoAAwBSJaQAApyeeJI4AP6atZbl+fVCfeG6m3HzZR+ceUjPCM5RSrcMDgAA",
  },
  "cert-internshala-web": {
    src: "/images/gallery/cert-internshala-web.webp",
    width: 1080,
    height: 736,
    blurDataURL: "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADQAQCdASoOAAoAAwBSJaQAAudi9Lh84AD++XMMjR/1QxGtgAA=",
  },
  "cert-coursera-ads": {
    src: "/images/gallery/cert-coursera-ads.webp",
    width: 1080,
    height: 818,
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACQAQCdASoOAAsAAwBSJaQAApn4qAAA/vA7J4KR+jAAX73IY1t4nA0lwAA=",
  },
  "cert-eduskills-android": {
    src: "/images/gallery/cert-eduskills-android.webp",
    width: 1080,
    height: 1477,
    blurDataURL: "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoOABMAPt1iqUyopiQiMAgBEBuJYwDCgGoRf/8NRMsKNRF64AD++QfwjhF5XyNNVLXAsFS45uIlVn2dO3vWyffqgV0VsHydTA8xNyrT+t5ndGQieladpl83GKFAAA==",
  },
  "wk-autocad": {
    src: "/images/gallery/wk-autocad.webp",
    width: 1080,
    height: 725,
    blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAQAgCdASoOAAkAAwBSJZwAAxf/un70ko+AAP73U4lybCl/te4IXyEjitEbehAA",
  },
  "wk-git": {
    src: "/images/gallery/wk-git.webp",
    width: 1079,
    height: 750,
    blurDataURL: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoOAAoAAwBSJQBOgCHvPPJTBAAA/uuWmklhDbsZk3Ni/7iWM57ljFgiK4AAAA==",
  },
  "wk-capx-llm": {
    src: "/images/gallery/wk-capx-llm.webp",
    width: 1080,
    height: 909,
    blurDataURL: "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoOAAwAAwBSJbAC7AEPC6nURAAA/vf/IrPFY27Bnh7YU3KrNWq0Vf93fV4mvwy1NMAAAA==",
  },
  "wk-tareeqa-hr": {
    src: "/images/gallery/wk-tareeqa-hr.webp",
    width: 1079,
    height: 696,
    blurDataURL: "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoOAAkAAwBSJQAAXP7VT1gAAP55P8xf4Q92dNRxEEmSQ3ikPuHdhjG+9UoggLCzPfvqKRazgAA=",
  },
  "comp-sih": {
    src: "/images/gallery/comp-sih.webp",
    width: 1080,
    height: 751,
    blurDataURL: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoOAAoAAwBSJZQCdH8AGKOh1Y4AAP7uKHHvjyVz0sfHLMJdfmv04JCD3JLbFgAA",
  },
  "comp-colossus": {
    src: "/images/gallery/comp-colossus.webp",
    width: 1079,
    height: 747,
    blurDataURL: "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoOAAoAAwBSJZwAAo7YTR4koAD+8GxNx6RHpg+U0qqD/6SEMla1KIqeUC1oB4AA",
  },
  "comp-cypherquest": {
    src: "/images/gallery/comp-cypherquest.webp",
    width: 1080,
    height: 748,
    blurDataURL: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoOAAoAAwBSJZQAAugswFU5xh2AAP7z8UqlNCk7mArKWn1Jhkyz4PqYsGSIBNrgaBNK076GF9AAAA==",
  },
  "comp-young-turks": {
    src: "/images/gallery/comp-young-turks.webp",
    width: 1080,
    height: 791,
    blurDataURL: "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoOAAoAAwBSJaQAAu058vZSAAD+sj/lq3+YYqS3h4DF89vSYBAAAA==",
  },
  "comp-aincat": {
    src: "/images/gallery/comp-aincat.webp",
    width: 1080,
    height: 793,
    blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoOAAoAAwBSJZQCdAEO99mLsAAA/vUxpTTbnRKVn0/nZ0emHHDshAAA",
  },
  "vol-agentic-ai-day": {
    src: "/images/gallery/vol-agentic-ai-day.webp",
    width: 1080,
    height: 772,
    blurDataURL: "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACQAQCdASoOAAoAAwBSJY1efU0AqkAA/vQJvO9KDDi2CCz48Y5J4en5tG7ExwAA",
  },
  "vol-hackzion": {
    src: "/images/gallery/vol-hackzion.webp",
    width: 1079,
    height: 790,
    blurDataURL: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoOAAoAAwBSJZwAApJg3xTgAPjhEgCOiw5ZRu2GFDZAAA==",
  },
  "vol-parishe": {
    src: "/images/gallery/vol-parishe.webp",
    width: 973,
    height: 731,
    blurDataURL: "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoOAAsAAwBSJZwAAp0UfOAAAP74vuy2aL8c7lu9+PW+JYEAAAA=",
  },
};

/** Returns undefined for ids with no processed file, so callers can fall back. */
export const img = (id: string): GalleryImage | undefined => gallery[id];
