// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run `npm run images` after swapping a portrait.

export const portraits = {
  hero: {
    src: "/images/portrait-hero.webp",
    width: 1100,
    height: 1082,
    blurDataURL: "data:image/webp;base64,UklGRkABAABXRUJQVlA4WAoAAAAQAAAADQAADQAAQUxQSKIAAAANgFvbtmplnef+vuCeWxkUYA3QH10Q0YRD9t3tbqSJiAiw7OrmOnx6fO4BBMdnq+7mJP94X2DkZ1tTub3d0esArGytnSzcTnpdUBYtHViezMeCOFxLkMSbqcPycC5MYeFN5ySFLQG8OppMvLxcun8rktmEKp9JBpYn89Fe7TpCGEUzGN4vX5YIIDk7TR++Z3KLGWkc7Z8fnztpMx6qKoJkextWUDggeAAAABACAJ0BKg4ADgADAFIlAE6P4AKDWcQl3oAA/vLpounCOW+BCBc42dmdxbWMKYWP2hrMzZY6hU8s/+0bxZIsSnTI5KmKtL/5vAdlAx3Aw0R94My1vOfY2i6D/VoOu48NtnriLuz9SomW/Sle6krRS1rm8/9YW4AAAA==",
  },
  plate: {
    src: "/images/portrait-plate.webp",
    width: 1000,
    height: 1250,
    blurDataURL: "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADwAwCdASoOABIAPt1apkyopSOiMAgBEBuJQBOmUABk9AxP3v3jKFyAAP7h4TDhdrykOYLWpIg+KMmBjWCcpoGY1IVqant6+bCygV56EqHqDzJRcJl3bHnKuPbrTq0c7Fuh4KDG8Z+Qwi6EL2TLVIjprSWUqKpiUAA=",
  },
} as const;
