/**
 * Optimises the certificate and event photographs.
 *
 *   npm run gallery
 *
 * Reads every file listed in gallery-manifest.mjs, writes a web-sized WebP into
 * public/images/gallery/, and regenerates lib/gallery-data.ts with the
 * dimensions and blur placeholder for each one. Nothing in the site references
 * the source folder — only the generated output.
 *
 * To add an image: drop it in the source folder, add an entry to the manifest,
 * re-run. To swap one: change the `file` in the manifest and re-run.
 */
import sharp from "sharp";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { manifest, SOURCE_DIR } from "./gallery-manifest.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT = path.join(ROOT, "public/images/gallery");

await fs.mkdir(OUT, { recursive: true });

/** Certificates are documents — keep them legible. Photos can be smaller. */
const WIDTH = { document: 1400, photo: 1600 };

async function blurDataUrl(buffer) {
  const buf = await sharp(buffer).resize(14).blur(1).webp({ quality: 45 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

const entries = [];
const missing = [];

for (const item of manifest) {
  const src = path.join(SOURCE_DIR, item.file);
  try {
    await fs.access(src);
  } catch {
    missing.push(item.file);
    continue;
  }

  const width = WIDTH[item.kind] ?? WIDTH.document;
  const pipeline = sharp(src).rotate().resize({ width, withoutEnlargement: true });

  const buf = await pipeline.clone().webp({ quality: 82, effort: 6 }).toBuffer();
  const meta = await sharp(buf).metadata();
  const outName = `${item.id}.webp`;

  await fs.writeFile(path.join(OUT, outName), buf);

  entries.push({
    id: item.id,
    src: `/images/gallery/${outName}`,
    width: meta.width,
    height: meta.height,
    blurDataURL: await blurDataUrl(buf),
    kb: (buf.length / 1024).toFixed(0),
  });
}

const body = entries
  .map(
    (e) => `  "${e.id}": {
    src: "${e.src}",
    width: ${e.width},
    height: ${e.height},
    blurDataURL: "${e.blurDataURL}",
  },`,
  )
  .join("\n");

await fs.writeFile(
  path.join(ROOT, "lib/gallery-data.ts"),
  `// GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Run \`npm run gallery\` after changing scripts/gallery-manifest.mjs.

export type GalleryImage = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export const gallery: Record<string, GalleryImage> = {
${body}
};

/** Returns undefined for ids with no processed file, so callers can fall back. */
export const img = (id: string): GalleryImage | undefined => gallery[id];
`,
);

const total = entries.reduce((sum, e) => sum + Number(e.kb), 0);
console.log(`${entries.length} images -> public/images/gallery (${total} KB total)`);
if (missing.length) console.warn(`missing from source folder: ${missing.join(", ")}`);
