/**
 * Derives every portrait asset the site needs from a single source headshot.
 *
 *   npm run images
 *
 * Source is a studio headshot on a white sweep. We flood-fill the background
 * from the borders (a plain luminance threshold would punch a hole through the
 * white shirt), feather the mask, and emit:
 *
 *   portrait-hero.png   cutout on transparency, for the dark hero
 *   portrait-plate.jpg  same cutout re-grounded on bone, for /about
 *
 * Swap SRC to change the photo; nothing else in the site needs to know.
 */
import sharp from "sharp";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = process.env.PORTRAIT_SRC ?? "C:/Users/ishwa/Desktop/photo.png";
const OUT = path.join(ROOT, "public/images");

const HI = 243; // luma at or above this, reached from a border, is background
const LO = 228; // luma below this is definitely subject
const BONE = "#e8e2d6";

const { data, info } = await sharp(SRC).removeAlpha().raw().toBuffer({ resolveWithObject: true });
const { width: W, height: H, channels: C } = info;

const luma = new Float32Array(W * H);
for (let i = 0, p = 0; i < W * H; i++, p += C) {
  luma[i] = 0.2126 * data[p] + 0.7152 * data[p + 1] + 0.0722 * data[p + 2];
}

const bg = new Uint8Array(W * H);
const stack = [];
const push = (i) => {
  if (!bg[i] && luma[i] >= HI) {
    bg[i] = 1;
    stack.push(i);
  }
};
for (let x = 0; x < W; x++) {
  push(x);
  push((H - 1) * W + x);
}
for (let y = 0; y < H; y++) {
  push(y * W);
  push(y * W + W - 1);
}
while (stack.length) {
  const i = stack.pop();
  const x = i % W;
  const y = (i / W) | 0;
  if (x > 0) push(i - 1);
  if (x < W - 1) push(i + 1);
  if (y > 0) push(i - W);
  if (y < H - 1) push(i + W);
}

const hard = Buffer.alloc(W * H);
for (let i = 0; i < W * H; i++) {
  if (!bg[i]) {
    hard[i] = 255;
  } else {
    const t = Math.min(1, Math.max(0, (luma[i] - LO) / (HI - LO)));
    hard[i] = Math.round(255 * (1 - t));
  }
}

// feather, then bias the ramp inward so the white sweep leaves no fringe
const soft = await sharp(hard, { raw: { width: W, height: H, channels: 1 } })
  .blur(1.2)
  .linear(1.35, -22)
  .toColourspace("b-w")
  .raw()
  .toBuffer({ resolveWithObject: true });
const SC = soft.info.channels;

const rgba = Buffer.alloc(W * H * 4);
for (let i = 0, s = 0, d = 0; i < W * H; i++, s += C, d += 4) {
  rgba[d] = data[s];
  rgba[d + 1] = data[s + 1];
  rgba[d + 2] = data[s + 2];
  rgba[d + 3] = soft.data[i * SC];
}

const cutout = sharp(rgba, { raw: { width: W, height: H, channels: 4 } });

// The site is a static export, so next/image cannot resize on demand — every
// asset is emitted here at exactly the size the layout asks for.
const heroPng = await cutout
  .clone()
  .trim({ threshold: 1 }) // drop the empty margin so the hero can crop tight
  .resize({ width: 1100, withoutEnlargement: true })
  .png()
  .toBuffer();

const heroMeta = await sharp(heroPng).metadata();
await sharp(heroPng).webp({ quality: 86, effort: 6 }).toFile(path.join(OUT, "portrait-hero.webp"));

// /about wants a photograph, not a cutout — put her back on a bone ground,
// warm the whole thing slightly so it sits with the palette
// two passes: sharp resizes before compositing regardless of call order,
// so ground her first, then crop
const grounded = await sharp({ create: { width: W, height: H, channels: 3, background: BONE } })
  .composite([{ input: await cutout.clone().png().toBuffer() }])
  .png()
  .toBuffer();

const platePng = await sharp(grounded)
  .resize(1000, 1250, { fit: "cover", position: "top" })
  .modulate({ saturation: 0.86 })
  .linear(1.02, -4)
  .png()
  .toBuffer();

await sharp(platePng).webp({ quality: 84, effort: 6 }).toFile(path.join(OUT, "portrait-plate.webp"));

/** Tiny inline preview so next/image can blur-up without a network round trip. */
async function blurDataUrl(input) {
  const buf = await sharp(input).resize(14).blur(1).webp({ quality: 45 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

await fs.writeFile(
  path.join(ROOT, "lib/image-data.ts"),
  `// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Run \`npm run images\` after swapping a portrait.

export const portraits = {
  hero: {
    src: "/images/portrait-hero.webp",
    width: ${heroMeta.width},
    height: ${heroMeta.height},
    blurDataURL: "${await blurDataUrl(heroPng)}",
  },
  plate: {
    src: "/images/portrait-plate.webp",
    width: 1000,
    height: 1250,
    blurDataURL: "${await blurDataUrl(platePng)}",
  },
} as const;
`,
);

const kb = async (f) => ((await fs.stat(path.join(OUT, f))).size / 1024).toFixed(0);
console.log(`portrait-hero.webp   ${heroMeta.width}×${heroMeta.height}   ${await kb("portrait-hero.webp")} KB`);
console.log(`portrait-plate.webp  1000×1250   ${await kb("portrait-plate.webp")} KB`);
console.log("lib/image-data.ts regenerated");
